### ISSUE TITLE
How to work with wav file

### ISSUE THREAD

**Issue by Sadam1195** [jnez71/adaptive_filter#1]
Hello, I have two questions. 
1. I was wondering if there was a way to apply this filter on .wav files instead of .mat file? like loading .wav files librosa and working with that, how to modify code for that?

2. What is in data['primary'] and data['reference'. I have played both, they seemed nothing but noise, how  is speech recovered from that?

**Comment by jnez71** [comment]
1. Just replace the call to `scipy.io.loadmat` with a wav-file reader of your choice. (There is probably one in `scipy.io`).

2. The "primary" data is a recording of Star Wars being played from a TV while a vacuum cleaner is on (you can listen to "corrupted_audio.wav" - but yeah it is nearly impossible to hear the TV in all the noise... for a human). The "reference" data is a recording of just the vacuum cleaner by itself (listen to "sample_of_corruption.wav").

The point of this demonstration is to show that the techniques of adaptive filtering can be used to recover the Star Wars audio given only a reference sample of the noise (hear the recovery in "recovered_SLMS.wav", and here is the original [movie clip](https://getyarn.io/yarn-clip/e2efa4a9-50c5-4e18-b3c9-c081eed95ee0)). This technology is what enables noise-cancelling headphones and more. In short, by hearing a reference of the noise, its statistical properties can be used to tune a filter "adaptively" that is "best" at removing that kind of noise. In this demo, the filter "learns" to cancel vacuum cleaners, and thus the Star Wars audio, though faint, can be recovered. More [here](http://www.cs.cmu.edu/~aarti/pubs/ANC.pdf).
![image](https://user-images.githubusercontent.com/15154558/61393789-bdd2a880-a88f-11e9-93ce-7cfbe691fc48.png)

**Comment by Sadam1195** [comment]
Thank you for the quick response and this illustration, everything makes much sense now. I still do have one think to ask, "it is possible say to clean an audio from noise when no audio['reference'] is available, when the signal source has only audio['primary'] (audio with noise)?

Consider this, I'm streaming audio live in noisy environment, then it is saved on disk, I have only one microphone to record (So I can't record both speech i.e : audio['primary'] and noise audio['reference'] at the same time), the recorded audio is speech with background noise (noise could be of any type) how to remove noise in that case? It is possible to clean audio when speech and noise are inseparable parts of a audio?

**Comment by jnez71** [comment]
In order to get high quality filtering, you need to know at least something about the system's statistics. In my case, I used a sample of the noise alone (a noise-reference adaptive filter). The filter adapts to be good at killing things that sound similar to the noise sample. Alternatively, one could use a sample of the speech alone (a signal-reference adaptive filter). Then the filter adapts to be good at killing things that sound _dissimilar_ to the speech sample (e.g., the noise). In either case, you will need a reference (either a sample of what you don't want to hear, or a sample of what you do want to hear, or both). If you have neither, then you will have to manually segment the data. For example, you could look at the frequency content of your noise+speech and see if there are any obvious features that will allow you to distinguish the noise from the speech. What you are doing then, is using the "reference" in your mind to "adapt" (design) a filter yourself, manually. The whole point of adaptive filtering is that, given a reference (in data rather than in your mind), the filter design is automated. If you have no idea what the signal you want to recover is and have no idea what the noise will be like, then it is not possible to design a filter in any way.

**Comment by Sadam1195** [comment]
Excellent. thank you so much. Now I know what to do and how to do what I am trying to do.
